# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-17 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRajasthan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.TextField(max_length=2)),
                ('postal_code', models.IntegerField(default=0)),
                ('place_name', models.TextField(max_length=20)),
                ('admin_name1', models.TextField(max_length=20)),
                ('admin_code1', models.IntegerField(default=0)),
                ('admin_name2', models.TextField(max_length=20)),
                ('admin_code2', models.IntegerField(default=0)),
                ('admin_name3', models.TextField(max_length=20)),
                ('admin_code3', models.IntegerField(default=0)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy', models.IntegerField(blank=True)),
            ],
            options={
                'ordering': ['postal_code'],
            },
        ),
    ]
