# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-19 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maphack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_name', models.TextField(max_length=20)),
                ('fathers_name', models.TextField(max_length=20)),
                ('address', models.TextField()),
                ('id_no', models.IntegerField()),
                ('card_status', models.TextField(default='Green Card')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'ordering': ['id_no'],
            },
        ),
    ]
