# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-19 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maphack', '0002_guides'),
    ]

    operations = [
        migrations.AddField(
            model_name='guides',
            name='mob_no',
            field=models.IntegerField(default=1800111363),
        ),
    ]
